@endpoint = http://localhost:3000/api/v1/cars

### Create a test car
# @name postACar
POST {{endpoint}} HTTP/1.1
x-api-key: blahblah
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Corolla"
}

###
@newCar = {{postACar.response.body._id}}

### Get all cars
GET {{endpoint}} HTTP/1.1
x-api-key: blahblah

### Get the test car
GET {{endpoint}}/{{newCar}} HTTP/1.1
x-api-key: blahblah

### Update the test car
PUT {{endpoint}}/{{newCar}} HTTP/1.1
x-api-key: blahblah
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Yaris"
}

### Delete the test car
DELETE {{endpoint}}/{{newCar}} HTTP/1.1
x-api-key: blahblah